//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_lab3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public System.Guid FlightID { get; set; }
        public int AirplaneID { get; set; }
        public int AirlineID { get; set; }
        public string FlightNumber { get; set; }
        public int Origin { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public int Destination { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public int FreeSeats { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
